version: '3.9'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create db:migrate db:seed && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
      - db-data:/myapp/db
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=sqlite3:/myapp/db/development.sqlite3

  python-worker:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "6400:6400"
    volumes:
      - ./autoform:/app
      - db-data:/myapp/db
    environment:
      - RAILS_SERVER=http://app:3000
    depends_on:
      - app

volumes:
  db-data: